// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package guildstate

import (
	"database/sql"
)

type GuildRecord struct {
	ID    string
	Value sql.NullString
}

type LeaderboardConfig struct {
	LbType     string
	GuildID    string
	ChannelID  string
	MessageIds sql.NullString
}
