// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package guildstate

import (
	"database/sql"
)

type GuildCoordinator struct {
	GuildID string
	UserID  string
	AddedBy string
	AddedAt int64
}

type GuildRecord struct {
	ID    string
	Value sql.NullString
}

type LeaderboardConfig struct {
	LbType     string
	GuildID    string
	ChannelID  string
	MessageIds sql.NullString
}
