// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: query.sql

package guildstate

import (
	"context"
	"database/sql"
)

const deleteGuildRecords = `-- name: DeleteGuildRecords :exec
DELETE FROM guild_record
WHERE id = ?
`

func (q *Queries) DeleteGuildRecords(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGuildRecords, id)
	return err
}

const deleteGuildState = `-- name: DeleteGuildState :exec
DELETE FROM guild_record
WHERE id = ?
`

func (q *Queries) DeleteGuildState(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGuildState, id)
	return err
}

const getAllGuildState = `-- name: GetAllGuildState :many
SELECT id, value FROM guild_record
`

func (q *Queries) GetAllGuildState(ctx context.Context) ([]GuildRecord, error) {
	rows, err := q.db.QueryContext(ctx, getAllGuildState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuildRecord
	for rows.Next() {
		var i GuildRecord
		if err := rows.Scan(&i.ID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuildState = `-- name: GetGuildState :one
SELECT id, value FROM guild_record
WHERE id = ? LIMIT 1
`

func (q *Queries) GetGuildState(ctx context.Context, id string) (GuildRecord, error) {
	row := q.db.QueryRowContext(ctx, getGuildState, id)
	var i GuildRecord
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}

const insertGuildState = `-- name: InsertGuildState :one
INSERT INTO guild_record (id, value)
VALUES (?, ?)
RETURNING id, value
`

type InsertGuildStateParams struct {
	ID    string
	Value sql.NullString
}

func (q *Queries) InsertGuildState(ctx context.Context, arg InsertGuildStateParams) (GuildRecord, error) {
	row := q.db.QueryRowContext(ctx, insertGuildState, arg.ID, arg.Value)
	var i GuildRecord
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}

const updateGuildState = `-- name: UpdateGuildState :execrows
UPDATE guild_record
SET value = ?
WHERE id = ?
`

type UpdateGuildStateParams struct {
	Value sql.NullString
	ID    string
}

func (q *Queries) UpdateGuildState(ctx context.Context, arg UpdateGuildStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGuildState, arg.Value, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
