// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package guildstate

import (
	"context"
	"database/sql"
)

const deleteGuildCoordinator = `-- name: DeleteGuildCoordinator :exec
DELETE FROM guild_coordinator WHERE guild_id = ? AND user_id = ?
`

type DeleteGuildCoordinatorParams struct {
	GuildID string
	UserID  string
}

func (q *Queries) DeleteGuildCoordinator(ctx context.Context, arg DeleteGuildCoordinatorParams) error {
	_, err := q.db.ExecContext(ctx, deleteGuildCoordinator, arg.GuildID, arg.UserID)
	return err
}

const deleteGuildRecords = `-- name: DeleteGuildRecords :exec
DELETE FROM guild_record
WHERE id = ?
`

func (q *Queries) DeleteGuildRecords(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGuildRecords, id)
	return err
}

const deleteGuildState = `-- name: DeleteGuildState :exec
DELETE FROM guild_record
WHERE id = ?
`

func (q *Queries) DeleteGuildState(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGuildState, id)
	return err
}

const deleteLeaderboardConfig = `-- name: DeleteLeaderboardConfig :exec
DELETE FROM leaderboard_config
WHERE lb_type = ? AND guild_id = ?
`

type DeleteLeaderboardConfigParams struct {
	LbType  string
	GuildID string
}

func (q *Queries) DeleteLeaderboardConfig(ctx context.Context, arg DeleteLeaderboardConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteLeaderboardConfig, arg.LbType, arg.GuildID)
	return err
}

const getAllGuildState = `-- name: GetAllGuildState :many
SELECT id, value FROM guild_record
`

func (q *Queries) GetAllGuildState(ctx context.Context) ([]GuildRecord, error) {
	rows, err := q.db.QueryContext(ctx, getAllGuildState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuildRecord
	for rows.Next() {
		var i GuildRecord
		if err := rows.Scan(&i.ID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLeaderboardConfigs = `-- name: GetAllLeaderboardConfigs :many
SELECT lb_type, guild_id, channel_id, message_ids
FROM leaderboard_config
ORDER BY lb_type, guild_id
`

// Returns every configured (lb_type, guild_id) pair - used by the weekly post task.
func (q *Queries) GetAllLeaderboardConfigs(ctx context.Context) ([]LeaderboardConfig, error) {
	rows, err := q.db.QueryContext(ctx, getAllLeaderboardConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardConfig
	for rows.Next() {
		var i LeaderboardConfig
		if err := rows.Scan(
			&i.LbType,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLeaderboardConfigsForGuild = `-- name: GetAllLeaderboardConfigsForGuild :many
SELECT lb_type, guild_id, channel_id, message_ids
FROM leaderboard_config
WHERE guild_id = ?
ORDER BY lb_type
`

func (q *Queries) GetAllLeaderboardConfigsForGuild(ctx context.Context, guildID string) ([]LeaderboardConfig, error) {
	rows, err := q.db.QueryContext(ctx, getAllLeaderboardConfigsForGuild, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardConfig
	for rows.Next() {
		var i LeaderboardConfig
		if err := rows.Scan(
			&i.LbType,
			&i.GuildID,
			&i.ChannelID,
			&i.MessageIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuildCoordinator = `-- name: GetGuildCoordinator :one
SELECT guild_id, user_id, added_by, added_at FROM guild_coordinator
WHERE guild_id = ? AND user_id = ? LIMIT 1
`

type GetGuildCoordinatorParams struct {
	GuildID string
	UserID  string
}

func (q *Queries) GetGuildCoordinator(ctx context.Context, arg GetGuildCoordinatorParams) (GuildCoordinator, error) {
	row := q.db.QueryRowContext(ctx, getGuildCoordinator, arg.GuildID, arg.UserID)
	var i GuildCoordinator
	err := row.Scan(
		&i.GuildID,
		&i.UserID,
		&i.AddedBy,
		&i.AddedAt,
	)
	return i, err
}

const getGuildCoordinators = `-- name: GetGuildCoordinators :many
SELECT guild_id, user_id, added_by, added_at FROM guild_coordinator
WHERE guild_id = ?
ORDER BY added_at ASC
`

func (q *Queries) GetGuildCoordinators(ctx context.Context, guildID string) ([]GuildCoordinator, error) {
	rows, err := q.db.QueryContext(ctx, getGuildCoordinators, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuildCoordinator
	for rows.Next() {
		var i GuildCoordinator
		if err := rows.Scan(
			&i.GuildID,
			&i.UserID,
			&i.AddedBy,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuildState = `-- name: GetGuildState :one

SELECT id, value FROM guild_record
WHERE id = ? LIMIT 1
`

// --- Guild Record ------------------------------------------------------------
func (q *Queries) GetGuildState(ctx context.Context, id string) (GuildRecord, error) {
	row := q.db.QueryRowContext(ctx, getGuildState, id)
	var i GuildRecord
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}

const getLeaderboardConfig = `-- name: GetLeaderboardConfig :one
SELECT lb_type, guild_id, channel_id, message_ids
FROM leaderboard_config
WHERE lb_type = ? AND guild_id = ?
`

type GetLeaderboardConfigParams struct {
	LbType  string
	GuildID string
}

func (q *Queries) GetLeaderboardConfig(ctx context.Context, arg GetLeaderboardConfigParams) (LeaderboardConfig, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardConfig, arg.LbType, arg.GuildID)
	var i LeaderboardConfig
	err := row.Scan(
		&i.LbType,
		&i.GuildID,
		&i.ChannelID,
		&i.MessageIds,
	)
	return i, err
}

const insertGuildCoordinator = `-- name: InsertGuildCoordinator :exec

INSERT INTO guild_coordinator (guild_id, user_id, added_by, added_at)
VALUES (?, ?, ?, ?)
`

type InsertGuildCoordinatorParams struct {
	GuildID string
	UserID  string
	AddedBy string
	AddedAt int64
}

// --- Guild Coordinator -------------------------------------------------------
func (q *Queries) InsertGuildCoordinator(ctx context.Context, arg InsertGuildCoordinatorParams) error {
	_, err := q.db.ExecContext(ctx, insertGuildCoordinator,
		arg.GuildID,
		arg.UserID,
		arg.AddedBy,
		arg.AddedAt,
	)
	return err
}

const insertGuildState = `-- name: InsertGuildState :one
INSERT INTO guild_record (id, value)
VALUES (?, ?)
RETURNING id, value
`

type InsertGuildStateParams struct {
	ID    string
	Value sql.NullString
}

func (q *Queries) InsertGuildState(ctx context.Context, arg InsertGuildStateParams) (GuildRecord, error) {
	row := q.db.QueryRowContext(ctx, insertGuildState, arg.ID, arg.Value)
	var i GuildRecord
	err := row.Scan(&i.ID, &i.Value)
	return i, err
}

const updateGuildState = `-- name: UpdateGuildState :execrows
UPDATE guild_record
SET value = ?
WHERE id = ?
`

type UpdateGuildStateParams struct {
	Value sql.NullString
	ID    string
}

func (q *Queries) UpdateGuildState(ctx context.Context, arg UpdateGuildStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGuildState, arg.Value, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateLeaderboardConfigMessageIDs = `-- name: UpdateLeaderboardConfigMessageIDs :exec
UPDATE leaderboard_config
SET message_ids = ?
WHERE lb_type = ? AND guild_id = ?
`

type UpdateLeaderboardConfigMessageIDsParams struct {
	MessageIds sql.NullString
	LbType     string
	GuildID    string
}

// Persist the message ID(s) written during the last post run.
func (q *Queries) UpdateLeaderboardConfigMessageIDs(ctx context.Context, arg UpdateLeaderboardConfigMessageIDsParams) error {
	_, err := q.db.ExecContext(ctx, updateLeaderboardConfigMessageIDs, arg.MessageIds, arg.LbType, arg.GuildID)
	return err
}

const upsertLeaderboardConfig = `-- name: UpsertLeaderboardConfig :exec

INSERT INTO leaderboard_config (lb_type, guild_id, channel_id, message_ids)
VALUES (?, ?, ?, ?)
ON CONFLICT(lb_type, guild_id) DO UPDATE SET
    channel_id  = excluded.channel_id,
    message_ids = excluded.message_ids
`

type UpsertLeaderboardConfigParams struct {
	LbType     string
	GuildID    string
	ChannelID  string
	MessageIds sql.NullString
}

// --- Leaderboard Config ------------------------------------------------------
// Insert or update a guild leaderboard channel configuration.
func (q *Queries) UpsertLeaderboardConfig(ctx context.Context, arg UpsertLeaderboardConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertLeaderboardConfig,
		arg.LbType,
		arg.GuildID,
		arg.ChannelID,
		arg.MessageIds,
	)
	return err
}
