// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package menno

import (
	"database/sql"
	"time"
)

type DataTimestamp struct {
	Key       string
	Timestamp time.Time
}

type Datum struct {
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	TargetArtifactID   sql.NullInt64
	ArtifactTypeID     sql.NullInt64
	ArtifactRarityID   sql.NullInt64
	ArtifactTier       sql.NullInt64
	TotalDrops         sql.NullInt64
	MissionType        sql.NullInt64
}
