// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package menno

import (
	"context"
	"database/sql"
	"time"
)

const createTimestamp = `-- name: CreateTimestamp :exec
INSERT INTO data_timestamp (key, timestamp) VALUES ('menno', CURRENT_TIMESTAMP)
`

func (q *Queries) CreateTimestamp(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTimestamp)
	return err
}

const deleteData = `-- name: DeleteData :exec
DELETE FROM data
`

func (q *Queries) DeleteData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteData)
	return err
}

const getDrops = `-- name: GetDrops :many
SELECT
    d.ship_type_id,
    d.ship_duration_type_id,
    d.ship_level,
    d.target_artifact_id,
    d.artifact_type_id,
    d.artifact_rarity_id,
    d.artifact_tier,
    d.total_drops AS total_drops,
    (
        SELECT COALESCE(SUM(d2.total_drops), 0)
        FROM data d2
        WHERE
            d2.ship_type_id = d.ship_type_id AND
            d2.ship_duration_type_id = d.ship_duration_type_id AND
            d2.ship_level = d.ship_level AND
            d2.target_artifact_id = d.target_artifact_id
    ) AS all_drops_value,
    COALESCE(
        CAST(d.total_drops AS REAL) /
        NULLIF((
            SELECT SUM(d2.total_drops)
            FROM data d2
            WHERE
                d2.ship_type_id = d.ship_type_id AND
                d2.ship_duration_type_id = d.ship_duration_type_id AND
                d2.ship_level = d.ship_level AND
                d2.target_artifact_id = d.target_artifact_id
        ), 0),
        0.0
    ) AS drop_rate
FROM data d
WHERE
    d.ship_type_id = ? AND
    d.ship_duration_type_id = ? AND
    d.ship_level = ? AND
    d.artifact_type_id = ?
ORDER BY drop_rate DESC
`

type GetDropsParams struct {
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	ArtifactTypeID     sql.NullInt64
}

type GetDropsRow struct {
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	TargetArtifactID   sql.NullInt64
	ArtifactTypeID     sql.NullInt64
	ArtifactRarityID   sql.NullInt64
	ArtifactTier       sql.NullInt64
	TotalDrops         sql.NullInt64
	AllDropsValue      interface{}
	DropRate           interface{}
}

func (q *Queries) GetDrops(ctx context.Context, arg GetDropsParams) ([]GetDropsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDrops,
		arg.ShipTypeID,
		arg.ShipDurationTypeID,
		arg.ShipLevel,
		arg.ArtifactTypeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDropsRow
	for rows.Next() {
		var i GetDropsRow
		if err := rows.Scan(
			&i.ShipTypeID,
			&i.ShipDurationTypeID,
			&i.ShipLevel,
			&i.TargetArtifactID,
			&i.ArtifactTypeID,
			&i.ArtifactRarityID,
			&i.ArtifactTier,
			&i.TotalDrops,
			&i.AllDropsValue,
			&i.DropRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimestamp = `-- name: GetTimestamp :one
SELECT timestamp FROM data_timestamp
WHERE key = 'menno' LIMIT 1
`

func (q *Queries) GetTimestamp(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getTimestamp)
	var timestamp time.Time
	err := row.Scan(&timestamp)
	return timestamp, err
}

const insertData = `-- name: InsertData :exec
INSERT INTO data (
    ship_type_id,
    ship_duration_type_id,
    ship_level,
    target_artifact_id,
    artifact_type_id,
    artifact_rarity_id,
    artifact_tier,
    total_drops,
    mission_type
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDataParams struct {
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	TargetArtifactID   sql.NullInt64
	ArtifactTypeID     sql.NullInt64
	ArtifactRarityID   sql.NullInt64
	ArtifactTier       sql.NullInt64
	TotalDrops         sql.NullInt64
	MissionType        sql.NullInt64
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) error {
	_, err := q.db.ExecContext(ctx, insertData,
		arg.ShipTypeID,
		arg.ShipDurationTypeID,
		arg.ShipLevel,
		arg.TargetArtifactID,
		arg.ArtifactTypeID,
		arg.ArtifactRarityID,
		arg.ArtifactTier,
		arg.TotalDrops,
		arg.MissionType,
	)
	return err
}

const updateData = `-- name: UpdateData :exec
UPDATE data
SET total_drops = ?
WHERE
    ship_type_id = ? AND
    ship_duration_type_id = ? AND
    ship_level = ? AND
    target_artifact_id = ? AND
    artifact_type_id = ? AND
    artifact_rarity_id = ? AND
    artifact_tier = ? AND
    mission_type = ?
`

type UpdateDataParams struct {
	TotalDrops         sql.NullInt64
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	TargetArtifactID   sql.NullInt64
	ArtifactTypeID     sql.NullInt64
	ArtifactRarityID   sql.NullInt64
	ArtifactTier       sql.NullInt64
	MissionType        sql.NullInt64
}

func (q *Queries) UpdateData(ctx context.Context, arg UpdateDataParams) error {
	_, err := q.db.ExecContext(ctx, updateData,
		arg.TotalDrops,
		arg.ShipTypeID,
		arg.ShipDurationTypeID,
		arg.ShipLevel,
		arg.TargetArtifactID,
		arg.ArtifactTypeID,
		arg.ArtifactRarityID,
		arg.ArtifactTier,
		arg.MissionType,
	)
	return err
}

const updateTimestamp = `-- name: UpdateTimestamp :exec
UPDATE data_timestamp
SET timestamp = CURRENT_TIMESTAMP
WHERE key = 'menno'
`

func (q *Queries) UpdateTimestamp(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateTimestamp)
	return err
}
