// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package menno

import (
	"context"
	"database/sql"
	"time"
)

const createTimestamp = `-- name: CreateTimestamp :exec
INSERT INTO data_timestamp (key, timestamp) VALUES ('menno', CURRENT_TIMESTAMP)
`

func (q *Queries) CreateTimestamp(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTimestamp)
	return err
}

const deleteData = `-- name: DeleteData :execrows
DELETE FROM data
WHERE   
    ship_type_id = ? AND
    ship_duration_type_id = ? AND
    ship_level = ? AND
    target_artifact_id = ? AND
    artifact_type_id = ? AND
    artifact_rarity_id = ? AND
    artifact_tier = ? AND
    mission_type = ?
`

type DeleteDataParams struct {
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	TargetArtifactID   sql.NullInt64
	ArtifactTypeID     sql.NullInt64
	ArtifactRarityID   sql.NullInt64
	ArtifactTier       sql.NullInt64
	MissionType        sql.NullInt64
}

func (q *Queries) DeleteData(ctx context.Context, arg DeleteDataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteData,
		arg.ShipTypeID,
		arg.ShipDurationTypeID,
		arg.ShipLevel,
		arg.TargetArtifactID,
		arg.ArtifactTypeID,
		arg.ArtifactRarityID,
		arg.ArtifactTier,
		arg.MissionType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTimestamp = `-- name: GetTimestamp :one
SELECT timestamp FROM data_timestamp
WHERE key = 'menno' LIMIT 1
`

func (q *Queries) GetTimestamp(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getTimestamp)
	var timestamp time.Time
	err := row.Scan(&timestamp)
	return timestamp, err
}

const insertData = `-- name: InsertData :execrows
INSERT INTO data (
    ship_type_id,
    ship_duration_type_id,
    ship_level,
    target_artifact_id,
    artifact_type_id,
    artifact_rarity_id,
    artifact_tier,
    total_drops,
    mission_type
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDataParams struct {
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	TargetArtifactID   sql.NullInt64
	ArtifactTypeID     sql.NullInt64
	ArtifactRarityID   sql.NullInt64
	ArtifactTier       sql.NullInt64
	TotalDrops         sql.NullInt64
	MissionType        sql.NullInt64
}

func (q *Queries) InsertData(ctx context.Context, arg InsertDataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertData,
		arg.ShipTypeID,
		arg.ShipDurationTypeID,
		arg.ShipLevel,
		arg.TargetArtifactID,
		arg.ArtifactTypeID,
		arg.ArtifactRarityID,
		arg.ArtifactTier,
		arg.TotalDrops,
		arg.MissionType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateData = `-- name: UpdateData :execrows
UPDATE data
SET total_drops = ?
WHERE
    ship_type_id = ? AND
    ship_duration_type_id = ? AND
    ship_level = ? AND
    target_artifact_id = ? AND
    artifact_type_id = ? AND
    artifact_rarity_id = ? AND
    artifact_tier = ? AND
    mission_type = ?
`

type UpdateDataParams struct {
	TotalDrops         sql.NullInt64
	ShipTypeID         sql.NullInt64
	ShipDurationTypeID sql.NullInt64
	ShipLevel          sql.NullInt64
	TargetArtifactID   sql.NullInt64
	ArtifactTypeID     sql.NullInt64
	ArtifactRarityID   sql.NullInt64
	ArtifactTier       sql.NullInt64
	MissionType        sql.NullInt64
}

func (q *Queries) UpdateData(ctx context.Context, arg UpdateDataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateData,
		arg.TotalDrops,
		arg.ShipTypeID,
		arg.ShipDurationTypeID,
		arg.ShipLevel,
		arg.TargetArtifactID,
		arg.ArtifactTypeID,
		arg.ArtifactRarityID,
		arg.ArtifactTier,
		arg.MissionType,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTimestamp = `-- name: UpdateTimestamp :exec
UPDATE data_timestamp
SET timestamp = CURRENT_TIMESTAMP
WHERE key = 'menno'
`

func (q *Queries) UpdateTimestamp(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, updateTimestamp)
	return err
}
