package ei

// DurationTypeName maps duration type IDs to their names
var DurationTypeName = map[int32]string{
	0: "Short",
	1: "Standard",
	2: "Extended",
}

// ShipTypeName maps ship type IDs to their names
var ShipTypeName = map[int32]string{
	0:  "Chicken One",
	1:  "Chicken Nine",
	2:  "Chicken Heavy",
	3:  "BCR",
	4:  "Quintillion Chicken",
	5:  "Cornish-Hen Corvette",
	6:  "Galeggtica",
	7:  "Defihent",
	8:  "Voyegger",
	9:  "Henerprise",
	10: "Atreggies Henliner",
}

// ArtifactTypeName maps artifact type IDs to their names
var ArtifactTypeName = map[int32]string{
	0:     "Lunar totem",
	1:     "Tachyon stone",
	2:     "Tachyon stone fragment",
	3:     "Neodymium medallion",
	4:     "Beak of Midas",
	5:     "Light of Eggendil",
	6:     "Demeters necklace",
	7:     "Vial of Martian dust",
	8:     "Gusset",
	9:     "The Chalice",
	10:    "Book of Basan",
	11:    "Phoenix feather",
	12:    "Tungsten Ankh",
	17:    "Gold meteorite",
	18:    "Tau ceti geode",
	21:    "Aurelian brooch",
	22:    "Carved rainstick",
	23:    "Puzzle cube",
	24:    "Quantum metronome",
	25:    "Ship in a bottle",
	26:    "Tachyon Deflector",
	27:    "Interstellar compass",
	28:    "Dilithium monocle",
	29:    "Titanium actuator",
	30:    "Mercurys lens",
	31:    "Dilithium stone",
	32:    "Shell stone",
	33:    "Lunar stone",
	34:    "Soul stone",
	36:    "Quantum stone",
	37:    "Terra stone",
	38:    "Life stone",
	39:    "Prophecy stone",
	40:    "Clarity stone",
	43:    "Solar titanium",
	44:    "Dilithium stone fragment",
	45:    "Shell stone fragment",
	46:    "Lunar stone fragment",
	47:    "Soul stone fragment",
	48:    "Prophecy stone fragment",
	49:    "Quantum stone fragment",
	50:    "Terra stone fragment",
	51:    "Life stone fragment",
	52:    "Clarity stone fragment",
	10000: "No target",
}

// ArtifactTypeNameVirtue maps artifact type IDs to their names for virtue artifacts
var ArtifactTypeNameVirtue = map[int32]string{
	0:  "Lunar totem",
	1:  "Tachyon stone",
	2:  "Tachyon stone fragment",
	3:  "Neodymium medallion",
	6:  "Demeters necklace",
	8:  "Gusset",
	12: "Tungsten Ankh",
	17: "Gold meteorite",
	18: "Tau ceti geode",
	23: "Puzzle cube",
	27: "Interstellar compass",
	33: "Lunar stone",
	36: "Quantum stone",
	43: "Solar titanium",
}
