// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package farmerstate

import (
	"database/sql"
	"time"
)

type CustomBanner struct {
	UserID    string
	GuildID   string
	ImageData []byte
	UpdatedAt time.Time
}

type FarmerGuildMembership struct {
	UserID  string
	GuildID string
}

type FarmerState struct {
	ID    string
	Key   string
	Value sql.NullString
}

type SuspectMission struct {
	UserID           string
	MissionID        string
	Ship             int64
	Status           int64
	DurationType     int64
	MissionType      int64
	Level            int64
	Capacity         int64
	QualityBump      float64
	TargetArtifact   int64
	DurationSeconds  float64
	StartTimeDerived float64
	BaseSeconds      float64
	EventMultiplier  float64
}

type Timer struct {
	ID                string
	UserID            string
	ChannelID         string
	MsgID             string
	Reminder          time.Time
	Message           string
	Duration          int64
	OriginalChannelID string
	OriginalMsgID     string
	Active            bool
}
