// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package farmerstate

import (
	"database/sql"
	"time"
)

type CustomBanner struct {
	UserID    string
	GuildID   string
	ImageData []byte
	UpdatedAt time.Time
}

type FarmerGuildMembership struct {
	UserID  string
	GuildID string
}

type FarmerState struct {
	ID    string
	Key   string
	Value sql.NullString
}
