// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package boost

import (
	"database/sql"
)

type ContractComplaint struct {
	Contractid string
	Complaint  string
}

type ContractDatum struct {
	Channelid  string
	Contractid string
	Coopid     string
	Value      sql.NullString
}

type ContractRole struct {
	Contractid string
	RoleName   string
}

type CustomOrderSession struct {
	Uuid         string
	ContractHash string
	ChannelID    string
	UserID       string
	Lines        string
	ExpiresAt    int64
}

type DefineOrderSession struct {
	Uuid         string
	ContractHash string
	ChannelID    string
	UserID       string
	TemplateJson string
	IsSaved      int64
	ExpiresAt    int64
}

type MissingContract struct {
	Contractid string
	Timestamp  int64
}
