// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package boost

import (
	"database/sql"
)

type ContractDatum struct {
	Channelid  string
	Contractid string
	Coopid     string
	Value      sql.NullString
}
