// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package boost

import (
	"database/sql"
)

type ContractComplaint struct {
	Contractid string
	Complaint  string
}

type ContractDatum struct {
	Channelid  string
	Contractid string
	Coopid     string
	Value      sql.NullString
}

type ContractRole struct {
	Contractid string
	RoleName   string
}
