name: Development
on: [push, pull_request]
jobs:
  test-build-upload:
    permissions:
      contents: read
    strategy:
      matrix:
        go-version: [1.25.1]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@main
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@main
      with:
          fetch-depth: 0
    - name: Audit
      run: make audit
    - name: Test
      run: make test
    - name: Build
      run: |
        mkdir -p output/{linux,freebsd}
        VERSION=$(git describe --tags)
        CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64  go build -ldflags "-s -X github.com/mkmccarty/TokenTimeBoostBot/version.GitHash=$(git describe --tags --always --long --dirty)" -o output/freebsd/boostbot-$VERSION-freebsd-amd64
        CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -ldflags "-s -X github.com/mkmccarty/TokenTimeBoostBot/version.GitHash=$(git describe --tags --always --long --dirty)" -o output/linux/boostbot-$VERSION-linux-arm
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64  go build -ldflags "-s -X github.com/mkmccarty/TokenTimeBoostBot/version.GitHash=$(git describe --tags --always --long --dirty)" -o output/linux/boostbot-$VERSION-linux-amd64
    - name: Upload linux
      if: startsWith(matrix.go-version,'1.25.1')
      uses: actions/upload-artifact@main
      with:
        name: boostbot-linux
        path: output/linux
    - name: Upload freebsd
      if: startsWith(matrix.go-version,'1.25.1')
      uses: actions/upload-artifact@main
      with:
        name: boostbot-freebsd
        path: output/freebsd        
